let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
let city = 'lahore';
console.log("Is city == 'lahore'? I predict True.");
console.log(city == 'lahore');
let bank = 'Habib Bank';
console.log("Is bank == 'Habib Bank'? I predict True.");
console.log(bank == 'Habib Bank');
let school = 'Message Grammer';
console.log("Is school == 'Message Grammer'? I predict True.");
console.log(school == 'Message Grammer');
let codingLanguage = 'type script';
console.log("Is codingLanguage == 'type script'? I predict True.");
console.log(codingLanguage == 'type script');
let bike = 'honda';
console.log("Is bike == 'suzuki'? I predict false.");
console.log(bike == 'suzuki');
let shoes = 'Nike';
console.log("Is shoes == 'Adidas'? I predict False.");
console.log(shoes == 'Adidas');
let mobile = 'Apple';
console.log("Is mobile == 'Samsung'? I predict false.");
console.log(mobile == 'Samsung');
let continent = 'Asia';
console.log("Is continent == 'europe'? I predict True.");
console.log(continent == 'europe');
let planet = 'earth';
console.log("Is planet == 'venus'? I predict True.");
console.log(planet == 'venus');
export {};
